// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package dep

import (
	"context"
	"github.com/go-kit/kit/log"
	zap2 "github.com/go-kit/kit/log/zap"
	"github.com/google/wire"
	"github.com/maestre3d/alexandria/author-service/internal/dependency"
	"github.com/maestre3d/alexandria/author-service/internal/infrastructure/config"
	"github.com/maestre3d/alexandria/author-service/pkg/author"
	"github.com/maestre3d/alexandria/author-service/pkg/author/usecase"
	"github.com/maestre3d/alexandria/author-service/pkg/shared"
	"github.com/maestre3d/alexandria/author-service/pkg/transport"
	"github.com/maestre3d/alexandria/author-service/pkg/transport/bind"
	"github.com/maestre3d/alexandria/author-service/pkg/transport/pb"
	"github.com/maestre3d/alexandria/author-service/pkg/transport/proxy"
	"github.com/maestre3d/alexandria/author-service/pkg/transport/tracer"
	"go.uber.org/zap"
	"go.uber.org/zap/zapcore"
)

// Injectors from wire.go:

func InjectTransportService() (*transport.TransportService, func(), error) {
	logger := provideLogger()
	iAuthorService, cleanup, err := provideAuthorService(logger)
	if err != nil {
		return nil, nil, err
	}
	context := provideContext()
	kernelConfig := config.NewKernelConfig(context, logger)
	zipkinTracer, cleanup2 := tracer.NewZipkinTracer(logger, kernelConfig)
	opentracingTracer := tracer.NewOpenTracer(logger, kernelConfig, zipkinTracer)
	authorServer := bind.NewAuthorRPCServer(iAuthorService, logger, opentracingTracer, zipkinTracer)
	rpcProxyHandlers := provideRPCProxyHandlers(authorServer)
	server, cleanup3 := proxy.NewRPCTransportProxy(rpcProxyHandlers, logger, kernelConfig)
	httpServer := shared.NewHTTPServer(logger, kernelConfig)
	authorHandler := bind.NewAuthorHandler(iAuthorService, logger, opentracingTracer, zipkinTracer)
	proxyHandlers := provideProxyHandlers(authorHandler)
	httpTransportProxy, cleanup4 := proxy.NewHTTPTransportProxy(logger, httpServer, kernelConfig, proxyHandlers)
	transportService := transport.NewTransportService(server, httpTransportProxy)
	return transportService, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var authorServiceSet = wire.NewSet(
	provideLogger,
	provideAuthorService,
)

var proxyHandlersSet = wire.NewSet(
	authorServiceSet, config.NewKernelConfig, tracer.NewOpenTracer, tracer.NewZipkinTracer, bind.NewAuthorHandler, provideProxyHandlers,
)

var httpProxySet = wire.NewSet(
	proxyHandlersSet,
	provideContext, shared.NewHTTPServer, proxy.NewHTTPTransportProxy,
)

var rpcProxyHandlersSet = wire.NewSet(bind.NewAuthorRPCServer, provideRPCProxyHandlers)

var rpcProxySet = wire.NewSet(
	rpcProxyHandlersSet, proxy.NewRPCTransportProxy,
)

func provideContext() context.Context {
	return context.Background()
}

func provideLogger() log.Logger {
	zapLogger, _ := zap.NewProduction()
	defer zapLogger.Sync()
	level := zapcore.Level(8)

	return zap2.NewZapSugarLogger(zapLogger, level)
}

func provideAuthorService(logger log.Logger) (usecase.IAuthorService, func(), error) {
	authorUseCase, cleanup, err := dependency.InjectAuthorUseCase()

	authorService := author.NewAuthorService(authorUseCase, logger)

	return authorService, cleanup, err
}

func provideProxyHandlers(authorHandler *bind.AuthorHandler) *proxy.ProxyHandlers {
	return &proxy.ProxyHandlers{authorHandler}
}

func provideRPCProxyHandlers(authorHandler pb.AuthorServer) *proxy.RPCProxyHandlers {
	return &proxy.RPCProxyHandlers{authorHandler}
}
