// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package dependency

import (
	"context"
	"github.com/go-kit/kit/log"
	zap2 "github.com/go-kit/kit/log/zap"
	"github.com/google/wire"
	"github.com/maestre3d/alexandria/media-service/internal/media/domain"
	"github.com/maestre3d/alexandria/media-service/internal/media/infrastructure"
	"github.com/maestre3d/alexandria/media-service/internal/media/interactor"
	"github.com/maestre3d/alexandria/media-service/internal/shared/infrastructure/config"
	"github.com/maestre3d/alexandria/media-service/internal/shared/infrastructure/persistence"
	"go.uber.org/zap"
	"go.uber.org/zap/zapcore"
)

// Injectors from wire.go:

func InjectMediaUseCase() (*interactor.MediaUseCase, func(), error) {
	logger := ProvideLogger()
	context := ProvideContext()
	kernelConfig := config.NewKernelConfig(context, logger)
	db, cleanup, err := persistence.NewPostgresPool(context, logger, kernelConfig)
	if err != nil {
		return nil, nil, err
	}
	client, cleanup2, err := persistence.NewRedisPool(logger, kernelConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	mediaDBMSRepository := infrastructure.NewMediaRDBMSRepository(db, client, logger, context)
	mediaUseCase := interactor.NewMediaUseCase(logger, mediaDBMSRepository)
	return mediaUseCase, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var configSet = wire.NewSet(
	ProvideContext,
	ProvideLogger, config.NewKernelConfig,
)

var postgresPoolSet = wire.NewSet(
	configSet, persistence.NewPostgresPool,
)

var mediaRepositorySet = wire.NewSet(
	postgresPoolSet, persistence.NewRedisPool, infrastructure.NewMediaRDBMSRepository, wire.Bind(new(domain.IMediaRepository), new(*infrastructure.MediaDBMSRepository)),
)

var mediaUseCaseSet = wire.NewSet(
	mediaRepositorySet, interactor.NewMediaUseCase,
)

func ProvideContext() context.Context {
	return context.Background()
}

func ProvideLogger() log.Logger {
	loggerZap, _ := zap.NewProduction()
	defer loggerZap.Sync()
	level := zapcore.Level(8)

	return zap2.NewZapSugarLogger(loggerZap, level)
}
