CREATE TABLE IF NOT EXISTS USERS (
	ID BIGSERIAL PRIMARY KEY NOT NULL,
	EXTERNAL_ID UUID UNIQUE NOT NULL,
	USERNAME VARCHAR(30) UNIQUE NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	GENDER VARCHAR(50) NOT NULL DEFAULT 'MALE',
	LOCALE VARCHAR(7) NOT NULL DEFAULT 'EN-US',
	PICTURE TEXT DEFAULT NULL,
	DELETED BOOL DEFAULT FALSE,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	DELETED_AT TIMESTAMP DEFAULT NULL
);
