CREATE TYPE USER_ROLE AS ENUM(
    'ROLE_ROOT',
    'ROLE_ADMIN',
    'ROLE_USER'
);

CREATE TYPE GENDER AS ENUM(
    'FEMALE',
    'MALE',
    'OTHER'
);

-- User entity, uses distributed ID w/ timestamp as ID and base64-encoded identifier as external ID
CREATE TABLE IF NOT EXISTS USERS (
	ID              BIGINT NOT NULL,
	EXTERNAL_ID     VARCHAR(128) NOT NULL,
	USERNAME        VARCHAR(30) UNIQUE NOT NULL,
	PASSWORD        TEXT NOT NULL,
	NAME            VARCHAR(50) NOT NULL,
	LAST_NAME       VARCHAR(50) NOT NULL,
	EMAIL           VARCHAR(320) NOT NULL,
	GENDER          GENDER NOT NULL DEFAULT 'MALE',
	LOCALE          VARCHAR(7) NOT NULL DEFAULT 'EN-US',
	PICTURE         TEXT DEFAULT NULL,
	ROLE            USER_ROLE DEFAULT 'ROLE_USER',
	CREATE_TIME     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATE_TIME     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	DELETE_TIME     TIMESTAMP DEFAULT NULL,
	DELETED         BOOL DEFAULT FALSE,
	ACTIVE          BOOL DEFAULT FALSE,
	VERIFIED        BOOL DEFAULT FALSE,
	PRIMARY KEY (ID, EXTERNAL_ID)
);
