-- LIST MEDIA BY CRITERIA
SELECT * FROM MEDIA
WHERE
(LOWER(TITLE) LIKE LOWER('%h%') OR LOWER(DISPLAY_NAME) LIKE LOWER('%h%')
OR LOWER(MEDIA_TYPE::TEXT) LIKE LOWER('%h%')) AND
MEDIA_TYPE = 'MEDIA_BOOK' AND 
MEDIA_ID >= (SELECT MEDIA_ID FROM MEDIA WHERE EXTERNAL_ID = 'e15162e7-d32f-49a9-8297-f8757764c80a' AND DELETED = FALSE) AND 
DELETED = FALSE
FETCH FIRST 2 ROWS ONLY;

-- LIST MEDIA BY TIMESTAMP
SELECT * FROM MEDIA WHERE
UPDATE_TIME <= (SELECT UPDATE_TIME FROM MEDIA WHERE EXTERNAL_ID = '30bf6ac3-5b54-4e12-91fc-3f42b32d4acc' AND DELETED = FALSE) AND 
DELETED = FALSE
ORDER BY UPDATE_TIME DESC
FETCH FIRST 3 ROWS ONLY;