CREATE TABLE IF NOT EXISTS BOOK(
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL UNIQUE,
    PUBLISHED_AT DATE NOT NULL DEFAULT CURRENT_DATE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPLOADED_BY BIGINT DEFAULT 0,
    AUTHOR BIGINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS BOOK_FAVORITE(
    BOOK_ID BIGINT REFERENCES BOOK(ID) ON DELETE CASCADE,
    LIKED_BY BIGINT NOT NULL,
    PRIMARY KEY(BOOK_ID, LIKED_BY)
);
