/******************************
**	File:   main.sql
**	Name:	Database migration script
**	Desc:	Main database migration script for Author microservice
**	Auth:	Alonso R
**	Lic:	MIT	
**	Date:	2020-04-14
*******************************/

CREATE TABLE IF NOT EXISTS AUTHOR(
	ID 				BIGSERIAL NOT NULL PRIMARY KEY,
	EXTERNAL_ID 	UUID NOT NULL UNIQUE,
	FIRST_NAME 		VARCHAR(255) NOT NULL,
	LAST_NAME 		VARCHAR(255) NOT NULL,
	DISPLAY_NAME 	VARCHAR(255) NOT NULL,
	BIRTH_DATE 		DATE NOT NULL DEFAULT CURRENT_DATE,
	CREATE_TIME 	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATE_TIME 	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	DELETE_TIME 	TIMESTAMP DEFAULT NULL,
	METADATA		TEXT DEFAULT NULL,
	DELETED 		BOOL DEFAULT FALSE
);