// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package dependency

import (
	"context"
	"github.com/alexandria-oss/core/config"
	"github.com/alexandria-oss/core/logger"
	"github.com/alexandria-oss/core/persistence"
	"github.com/google/wire"
	"github.com/maestre3d/alexandria/media-service/internal/domain"
	"github.com/maestre3d/alexandria/media-service/internal/infrastructure"
	"github.com/maestre3d/alexandria/media-service/internal/interactor"
)

// Injectors from wire.go:

func InjectMediaUseCase() (*interactor.MediaUseCase, func(), error) {
	logLogger := logger.NewZapLogger()
	context := provideContext()
	kernel, err := config.NewKernel(context)
	if err != nil {
		return nil, nil, err
	}
	db, cleanup, err := persistence.NewPostgresPool(context, kernel)
	if err != nil {
		return nil, nil, err
	}
	client, cleanup2, err := persistence.NewRedisPool(kernel)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	mediaPQRepository := infrastructure.NewMediaPQRepository(db, client, logLogger)
	mediaUseCase := interactor.NewMediaUseCase(logLogger, mediaPQRepository)
	return mediaUseCase, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var Ctx = context.Background()

var dataSet = wire.NewSet(
	provideContext, config.NewKernel, persistence.NewPostgresPool, persistence.NewRedisPool,
)

var mediaSet = wire.NewSet(
	dataSet, logger.NewZapLogger, wire.Bind(new(domain.MediaRepository), new(*infrastructure.MediaPQRepository)), infrastructure.NewMediaPQRepository, interactor.NewMediaUseCase,
)

func provideContext() context.Context {
	return Ctx
}
