// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package dependency

import (
	"context"
	"github.com/alexandria-oss/core/config"
	"github.com/alexandria-oss/core/logger"
	"github.com/alexandria-oss/core/persistence"
	"github.com/google/wire"
	"github.com/maestre3d/alexandria/media-service/internal/domain"
	"github.com/maestre3d/alexandria/media-service/internal/infrastructure"
	"github.com/maestre3d/alexandria/media-service/internal/interactor"
)

// Injectors from wire.go:

func InjectMediaUseCase() (*interactor.Media, func(), error) {
	logLogger := logger.NewZapLogger()
	context := provideContext()
	kernel, err := config.NewKernel(context)
	if err != nil {
		return nil, nil, err
	}
	db, cleanup, err := persistence.NewPostgresPool(context, kernel)
	if err != nil {
		return nil, nil, err
	}
	client, cleanup2, err := persistence.NewRedisPool(kernel)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	mediaPQRepository := infrastructure.NewMediaPQRepository(db, client, logLogger)
	mediaKafkaEvent := infrastructure.NewMediaKafakaEvent(kernel)
	media := interactor.NewMedia(logLogger, mediaPQRepository, mediaKafkaEvent)
	return media, func() {
		cleanup2()
		cleanup()
	}, nil
}

func InjectMediaSAGAUseCase() (*interactor.MediaSAGA, func(), error) {
	context := provideContext()
	kernel, err := config.NewKernel(context)
	if err != nil {
		return nil, nil, err
	}
	db, cleanup, err := persistence.NewPostgresPool(context, kernel)
	if err != nil {
		return nil, nil, err
	}
	client, cleanup2, err := persistence.NewRedisPool(kernel)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	logLogger := logger.NewZapLogger()
	mediaPQRepository := infrastructure.NewMediaPQRepository(db, client, logLogger)
	mediaKafkaEvent := infrastructure.NewMediaKafakaEvent(kernel)
	mediaSAGAKafkaEvent := infrastructure.NewMediaSAGAKafkaEvent(kernel)
	mediaSAGA := interactor.NewMediaSAGA(mediaPQRepository, mediaKafkaEvent, mediaSAGAKafkaEvent, logLogger)
	return mediaSAGA, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var Ctx = context.Background()

var dataSet = wire.NewSet(
	provideContext, config.NewKernel, persistence.NewPostgresPool, persistence.NewRedisPool, logger.NewZapLogger, wire.Bind(new(domain.MediaRepository), new(*infrastructure.MediaPQRepository)), infrastructure.NewMediaPQRepository,
)

var eventSet = wire.NewSet(wire.Bind(new(domain.MediaEvent), new(*infrastructure.MediaKafkaEvent)), infrastructure.NewMediaKafakaEvent)

func provideContext() context.Context {
	return Ctx
}
